// Copyright 2023 The Forgotten Server Authors. All rights reserved.
// Use of this source code is governed by the GPL-2.0 License that can be found in the LICENSE file.

#ifndef FS_ENUMS_H
#define FS_ENUMS_H

enum RuleViolationType_t : uint8_t
{
	REPORT_TYPE_NAME = 0,
	REPORT_TYPE_STATEMENT = 1,
	REPORT_TYPE_BOT = 2
};

enum RuleViolationReasons_t : uint8_t
{
	REPORT_REASON_NAMEINAPPROPRIATE = 0,
	REPORT_REASON_NAMEPOORFORMATTED = 1,
	REPORT_REASON_NAMEADVERTISING = 2,
	REPORT_REASON_NAMEUNFITTING = 3,
	REPORT_REASON_NAMERULEVIOLATION = 4,
	REPORT_REASON_INSULTINGSTATEMENT = 5,
	REPORT_REASON_SPAMMING = 6,
	REPORT_REASON_ADVERTISINGSTATEMENT = 7,
	REPORT_REASON_UNFITTINGSTATEMENT = 8,
	REPORT_REASON_LANGUAGESTATEMENT = 9,
	REPORT_REASON_DISCLOSURE = 10,
	REPORT_REASON_RULEVIOLATION = 11,
	REPORT_REASON_STATEMENT_BUGABUSE = 12,
	REPORT_REASON_UNOFFICIALSOFTWARE = 13,
	REPORT_REASON_PRETENDING = 14,
	REPORT_REASON_HARASSINGOWNERS = 15,
	REPORT_REASON_FALSEINFO = 16,
	REPORT_REASON_ACCOUNTSHARING = 17,
	REPORT_REASON_STEALINGDATA = 18,
	REPORT_REASON_SERVICEATTACKING = 19,
	REPORT_REASON_SERVICEAGREEMENT = 20
};

enum BugReportType_t : uint8_t
{
	BUG_CATEGORY_MAP = 0,
	BUG_CATEGORY_TYPO = 1,
	BUG_CATEGORY_TECHNICAL = 2,
	BUG_CATEGORY_OTHER = 3
};

enum ThreadState
{
	THREAD_STATE_RUNNING,
	THREAD_STATE_CLOSING,
	THREAD_STATE_TERMINATED,
};

enum itemAttrTypes : uint32_t
{
	ITEM_ATTRIBUTE_NONE,

	ITEM_ATTRIBUTE_ACTIONID = 1 << 0,
	ITEM_ATTRIBUTE_UNIQUEID = 1 << 1,
	ITEM_ATTRIBUTE_DESCRIPTION = 1 << 2,
	ITEM_ATTRIBUTE_TEXT = 1 << 3,
	ITEM_ATTRIBUTE_DATE = 1 << 4,
	ITEM_ATTRIBUTE_WRITER = 1 << 5,
	ITEM_ATTRIBUTE_NAME = 1 << 6,
	ITEM_ATTRIBUTE_ARTICLE = 1 << 7,
	ITEM_ATTRIBUTE_PLURALNAME = 1 << 8,
	ITEM_ATTRIBUTE_WEIGHT = 1 << 9,
	ITEM_ATTRIBUTE_ATTACK = 1 << 10,
	ITEM_ATTRIBUTE_DEFENSE = 1 << 11,
	ITEM_ATTRIBUTE_EXTRADEFENSE = 1 << 12,
	ITEM_ATTRIBUTE_ARMOR = 1 << 13,
	ITEM_ATTRIBUTE_HITCHANCE = 1 << 14,
	ITEM_ATTRIBUTE_SHOOTRANGE = 1 << 15,
	ITEM_ATTRIBUTE_OWNER = 1 << 16,
	ITEM_ATTRIBUTE_DURATION = 1 << 17,
	ITEM_ATTRIBUTE_DECAYSTATE = 1 << 18,
	ITEM_ATTRIBUTE_CORPSEOWNER = 1 << 19,
	ITEM_ATTRIBUTE_CHARGES = 1 << 20,
	ITEM_ATTRIBUTE_FLUIDTYPE = 1 << 21,
	ITEM_ATTRIBUTE_DOORID = 1 << 22,
	ITEM_ATTRIBUTE_DECAYTO = 1 << 23,
	ITEM_ATTRIBUTE_WRAPID = 1 << 24,
	ITEM_ATTRIBUTE_STOREITEM = 1 << 25,
	ITEM_ATTRIBUTE_ATTACK_SPEED = 1 << 26,
	ITEM_ATTRIBUTE_OPENCONTAINER = 1 << 27,

	ITEM_ATTRIBUTE_CUSTOM = 1U << 31
};

enum VipStatus_t : uint8_t
{
	VIPSTATUS_OFFLINE = 0,
	VIPSTATUS_ONLINE = 1,
	VIPSTATUS_PENDING = 2,
	VIPSTATUS_TRAINING = 3
};

enum MarketAction_t
{
	MARKETACTION_BUY = 0,
	MARKETACTION_SELL = 1,
};

enum MarketRequest_t
{
	MARKETREQUEST_OWN_HISTORY = 1,
	MARKETREQUEST_OWN_OFFERS = 2,
	MARKETREQUEST_ITEM = 3,
};

enum MarketOfferState_t
{
	OFFERSTATE_ACTIVE = 0,
	OFFERSTATE_CANCELLED = 1,
	OFFERSTATE_EXPIRED = 2,
	OFFERSTATE_ACCEPTED = 3,

	OFFERSTATE_ACCEPTEDEX = 255,
};

enum ChannelEvent_t : uint8_t
{
	CHANNELEVENT_JOIN = 0,
	CHANNELEVENT_LEAVE = 1,
	CHANNELEVENT_INVITE = 2,
	CHANNELEVENT_EXCLUDE = 3,
};

enum CreatureType_t : uint8_t
{
	CREATURETYPE_PLAYER = 0,
	CREATURETYPE_MONSTER = 1,
	CREATURETYPE_NPC = 2,
	CREATURETYPE_SUMMON_OWN = 3,
	CREATURETYPE_SUMMON_OTHERS = 4,
	CREATURETYPE_HIDDEN = 5,
};

enum OperatingSystem_t : uint8_t
{
	CLIENTOS_NONE = 0,

	CLIENTOS_LINUX = 1,
	CLIENTOS_WINDOWS = 2,
	CLIENTOS_FLASH = 3,
	CLIENTOS_QT_LINUX = 4,
	CLIENTOS_QT_WINDOWS = 5,
	CLIENTOS_QT_MAC = 6,
	CLIENTOS_QT_LINUX2 = 7,

	CLIENTOS_OTCLIENT_LINUX = 10,
	CLIENTOS_OTCLIENT_WINDOWS = 11,
	CLIENTOS_OTCLIENT_MAC = 12,
};

enum SpellGroup_t : uint8_t
{
	SPELLGROUP_NONE = 0,
	SPELLGROUP_ATTACK = 1,
	SPELLGROUP_HEALING = 2,
	SPELLGROUP_SUPPORT = 3,
	SPELLGROUP_SPECIAL = 4,
	// SPELLGROUP_CONJURE = 5,
	SPELLGROUP_CRIPPLING = 6,
	SPELLGROUP_FOCUS = 7,
	SPELLGROUP_ULTIMATESTRIKES = 8,
};

enum SpellType_t : uint8_t
{
	SPELL_UNDEFINED = 0,
	SPELL_INSTANT = 1,
	SPELL_RUNE = 2,
};

enum AccountType_t : uint8_t
{
	ACCOUNT_TYPE_NORMAL = 1,
	ACCOUNT_TYPE_TUTOR = 2,
	ACCOUNT_TYPE_SENIORTUTOR = 3,
	ACCOUNT_TYPE_GAMEMASTER = 4,
	ACCOUNT_TYPE_COMMUNITYMANAGER = 5,
	ACCOUNT_TYPE_GOD = 6
};

enum RaceType_t : uint8_t
{
	RACE_NONE,
	RACE_VENOM,
	RACE_BLOOD,
	RACE_UNDEAD,
	RACE_FIRE,
	RACE_ENERGY,
	RACE_INK,
};

enum CombatType_t : uint16_t
{
	COMBAT_NONE = 0,

	COMBAT_PHYSICALDAMAGE = 1 << 0,
	COMBAT_ENERGYDAMAGE = 1 << 1,
	COMBAT_EARTHDAMAGE = 1 << 2,
	COMBAT_FIREDAMAGE = 1 << 3,
	COMBAT_UNDEFINEDDAMAGE = 1 << 4,
	COMBAT_LIFEDRAIN = 1 << 5,
	COMBAT_MANADRAIN = 1 << 6,
	COMBAT_HEALING = 1 << 7,
	COMBAT_DROWNDAMAGE = 1 << 8,
	COMBAT_ICEDAMAGE = 1 << 9,
	COMBAT_HOLYDAMAGE = 1 << 10,
	COMBAT_DEATHDAMAGE = 1 << 11,

	COMBAT_COUNT = 12
};

enum CombatParam_t
{
	COMBAT_PARAM_TYPE,
	COMBAT_PARAM_EFFECT,
	COMBAT_PARAM_DISTANCEEFFECT,
	COMBAT_PARAM_BLOCKSHIELD,
	COMBAT_PARAM_BLOCKARMOR,
	COMBAT_PARAM_TARGETCASTERORTOPMOST,
	COMBAT_PARAM_CREATEITEM,
	COMBAT_PARAM_AGGRESSIVE,
	COMBAT_PARAM_DISPEL,
	COMBAT_PARAM_USECHARGES,
};

enum CallBackParam_t
{
	CALLBACK_PARAM_LEVELMAGICVALUE,
	CALLBACK_PARAM_SKILLVALUE,
	CALLBACK_PARAM_TARGETTILE,
	CALLBACK_PARAM_TARGETCREATURE,
};

enum ConditionParam_t
{
	CONDITION_PARAM_OWNER = 1,
	CONDITION_PARAM_TICKS = 2,
	// CONDITION_PARAM_OUTFIT = 3,
	CONDITION_PARAM_HEALTHGAIN = 4,
	CONDITION_PARAM_HEALTHTICKS = 5,
	CONDITION_PARAM_MANAGAIN = 6,
	CONDITION_PARAM_MANATICKS = 7,
	CONDITION_PARAM_DELAYED = 8,
	CONDITION_PARAM_SPEED = 9,
	CONDITION_PARAM_LIGHT_LEVEL = 10,
	CONDITION_PARAM_LIGHT_COLOR = 11,
	CONDITION_PARAM_SOULGAIN = 12,
	CONDITION_PARAM_SOULTICKS = 13,
	CONDITION_PARAM_MINVALUE = 14,
	CONDITION_PARAM_MAXVALUE = 15,
	CONDITION_PARAM_STARTVALUE = 16,
	CONDITION_PARAM_TICKINTERVAL = 17,
	CONDITION_PARAM_FORCEUPDATE = 18,
	CONDITION_PARAM_SKILL_MELEE = 19,
	CONDITION_PARAM_SKILL_FIST = 20,
	CONDITION_PARAM_SKILL_CLUB = 21,
	CONDITION_PARAM_SKILL_SWORD = 22,
	CONDITION_PARAM_SKILL_AXE = 23,
	CONDITION_PARAM_SKILL_DISTANCE = 24,
	CONDITION_PARAM_SKILL_SHIELD = 25,
	CONDITION_PARAM_SKILL_FISHING = 26,
	CONDITION_PARAM_STAT_MAXHITPOINTS = 27,
	CONDITION_PARAM_STAT_MAXMANAPOINTS = 28,
	// CONDITION_PARAM_STAT_SOULPOINTS = 29,
	CONDITION_PARAM_STAT_MAGICPOINTS = 30,
	CONDITION_PARAM_STAT_MAXHITPOINTSPERCENT = 31,
	CONDITION_PARAM_STAT_MAXMANAPOINTSPERCENT = 32,
	// CONDITION_PARAM_STAT_SOULPOINTSPERCENT = 33,
	CONDITION_PARAM_STAT_MAGICPOINTSPERCENT = 34,
	CONDITION_PARAM_PERIODICDAMAGE = 35,
	CONDITION_PARAM_SKILL_MELEEPERCENT = 36,
	CONDITION_PARAM_SKILL_FISTPERCENT = 37,
	CONDITION_PARAM_SKILL_CLUBPERCENT = 38,
	CONDITION_PARAM_SKILL_SWORDPERCENT = 39,
	CONDITION_PARAM_SKILL_AXEPERCENT = 40,
	CONDITION_PARAM_SKILL_DISTANCEPERCENT = 41,
	CONDITION_PARAM_SKILL_SHIELDPERCENT = 42,
	CONDITION_PARAM_SKILL_FISHINGPERCENT = 43,
	CONDITION_PARAM_BUFF_SPELL = 44,
	CONDITION_PARAM_SUBID = 45,
	CONDITION_PARAM_FIELD = 46,
	CONDITION_PARAM_DISABLE_DEFENSE = 47,
	CONDITION_PARAM_SPECIALSKILL_CRITICALHITCHANCE = 48,
	CONDITION_PARAM_SPECIALSKILL_CRITICALHITAMOUNT = 49,
	CONDITION_PARAM_SPECIALSKILL_LIFELEECHCHANCE = 50,
	CONDITION_PARAM_SPECIALSKILL_LIFELEECHAMOUNT = 51,
	CONDITION_PARAM_SPECIALSKILL_MANALEECHCHANCE = 52,
	CONDITION_PARAM_SPECIALSKILL_MANALEECHAMOUNT = 53,
	CONDITION_PARAM_AGGRESSIVE = 54,
	CONDITION_PARAM_DRUNKENNESS = 55,
	CONDITION_PARAM_MANASHIELD_BREAKABLE = 56,
};

enum BlockType_t : uint8_t
{
	BLOCK_NONE,
	BLOCK_DEFENSE,
	BLOCK_ARMOR,
	BLOCK_IMMUNITY
};

enum skills_t : uint8_t
{
	SKILL_FIST = 0,
	SKILL_CLUB = 1,
	SKILL_SWORD = 2,
	SKILL_AXE = 3,
	SKILL_DISTANCE = 4,
	SKILL_SHIELD = 5,
	SKILL_FISHING = 6,

	SKILL_MAGLEVEL = 7,
	SKILL_LEVEL = 8,

	SKILL_FIRST = SKILL_FIST,
	SKILL_LAST = SKILL_FISHING
};

enum stats_t
{
	STAT_MAXHITPOINTS,
	STAT_MAXMANAPOINTS,
	STAT_SOULPOINTS, // unused
	STAT_MAGICPOINTS,

	STAT_FIRST = STAT_MAXHITPOINTS,
	STAT_LAST = STAT_MAGICPOINTS
};

enum SpecialSkills_t
{
	SPECIALSKILL_CRITICALHITCHANCE,
	SPECIALSKILL_CRITICALHITAMOUNT,
	SPECIALSKILL_LIFELEECHCHANCE,
	SPECIALSKILL_LIFELEECHAMOUNT,
	SPECIALSKILL_MANALEECHCHANCE,
	SPECIALSKILL_MANALEECHAMOUNT,

	SPECIALSKILL_FIRST = SPECIALSKILL_CRITICALHITCHANCE,
	SPECIALSKILL_LAST = SPECIALSKILL_MANALEECHAMOUNT
};

enum formulaType_t
{
	COMBAT_FORMULA_UNDEFINED,
	COMBAT_FORMULA_LEVELMAGIC,
	COMBAT_FORMULA_SKILL,
	COMBAT_FORMULA_DAMAGE,
};

enum ConditionType_t
{
	CONDITION_NONE,

	CONDITION_POISON = 1 << 0,
	CONDITION_FIRE = 1 << 1,
	CONDITION_ENERGY = 1 << 2,
	CONDITION_BLEEDING = 1 << 3,
	CONDITION_HASTE = 1 << 4,
	CONDITION_PARALYZE = 1 << 5,
	CONDITION_OUTFIT = 1 << 6,
	CONDITION_INVISIBLE = 1 << 7,
	CONDITION_LIGHT = 1 << 8,
	CONDITION_MANASHIELD = 1 << 9,
	CONDITION_INFIGHT = 1 << 10,
	CONDITION_DRUNK = 1 << 11,
	CONDITION_EXHAUST_WEAPON = 1 << 12, // unused
	CONDITION_REGENERATION = 1 << 13,
	CONDITION_SOUL = 1 << 14,
	CONDITION_DROWN = 1 << 15,
	CONDITION_MUTED = 1 << 16,
	CONDITION_CHANNELMUTEDTICKS = 1 << 17,
	CONDITION_YELLTICKS = 1 << 18,
	CONDITION_ATTRIBUTES = 1 << 19,
	CONDITION_FREEZING = 1 << 20,
	CONDITION_DAZZLED = 1 << 21,
	CONDITION_CURSED = 1 << 22,
	CONDITION_EXHAUST_COMBAT = 1 << 23, // unused
	CONDITION_EXHAUST_HEAL = 1 << 24,   // unused
	CONDITION_PACIFIED = 1 << 25,
	CONDITION_SPELLCOOLDOWN = 1 << 26,
	CONDITION_SPELLGROUPCOOLDOWN = 1 << 27,
	CONDITION_ROOT = 1 << 28,
	CONDITION_MANASHIELD_BREAKABLE = 1 << 29,
};

enum ConditionId_t : int8_t
{
	CONDITIONID_DEFAULT = -1,
	CONDITIONID_COMBAT,
	CONDITIONID_HEAD,
	CONDITIONID_NECKLACE,
	CONDITIONID_BACKPACK,
	CONDITIONID_ARMOR,
	CONDITIONID_RIGHT,
	CONDITIONID_LEFT,
	CONDITIONID_LEGS,
	CONDITIONID_FEET,
	CONDITIONID_RING,
	CONDITIONID_AMMO,
};

enum PlayerSex_t : uint8_t
{
	PLAYERSEX_FEMALE = 0,
	PLAYERSEX_MALE = 1,

	PLAYERSEX_LAST = PLAYERSEX_MALE
};

inline constexpr uint16_t VOCATION_NONE = 0;

enum ReturnValue
{
	RETURNVALUE_NOERROR,
	RETURNVALUE_NOTPOSSIBLE,
	RETURNVALUE_NOTENOUGHROOM,
	RETURNVALUE_PLAYERISPZLOCKED,
	RETURNVALUE_PLAYERISNOTINVITED,
	RETURNVALUE_CANNOTTHROW,
	RETURNVALUE_THEREISNOWAY,
	RETURNVALUE_DESTINATIONOUTOFREACH,
	RETURNVALUE_CREATUREBLOCK,
	RETURNVALUE_NOTMOVEABLE,
	RETURNVALUE_DROPTWOHANDEDITEM,
	RETURNVALUE_BOTHHANDSNEEDTOBEFREE,
	RETURNVALUE_CANONLYUSEONEWEAPON,
	RETURNVALUE_NEEDEXCHANGE,
	RETURNVALUE_CANNOTBEDRESSED,
	RETURNVALUE_PUTTHISOBJECTINYOURHAND,
	RETURNVALUE_PUTTHISOBJECTINBOTHHANDS,
	RETURNVALUE_TOOFARAWAY,
	RETURNVALUE_FIRSTGODOWNSTAIRS,
	RETURNVALUE_FIRSTGOUPSTAIRS,
	RETURNVALUE_CONTAINERNOTENOUGHROOM,
	RETURNVALUE_NOTENOUGHCAPACITY,
	RETURNVALUE_CANNOTPICKUP,
	RETURNVALUE_THISISIMPOSSIBLE,
	RETURNVALUE_DEPOTISFULL,
	RETURNVALUE_CREATUREDOESNOTEXIST,
	RETURNVALUE_CANNOTUSETHISOBJECT,
	RETURNVALUE_PLAYERWITHTHISNAMEISNOTONLINE,
	RETURNVALUE_NOTREQUIREDLEVELTOUSERUNE,
	RETURNVALUE_YOUAREALREADYTRADING,
	RETURNVALUE_THISPLAYERISALREADYTRADING,
	RETURNVALUE_YOUMAYNOTLOGOUTDURINGAFIGHT,
	RETURNVALUE_DIRECTPLAYERSHOOT,
	RETURNVALUE_NOTENOUGHLEVEL,
	RETURNVALUE_NOTENOUGHMAGICLEVEL,
	RETURNVALUE_NOTENOUGHMANA,
	RETURNVALUE_NOTENOUGHSOUL,
	RETURNVALUE_YOUAREEXHAUSTED,
	RETURNVALUE_YOUCANNOTUSEOBJECTSTHATFAST,
	RETURNVALUE_PLAYERISNOTREACHABLE,
	RETURNVALUE_CANONLYUSETHISRUNEONCREATURES,
	RETURNVALUE_ACTIONNOTPERMITTEDINPROTECTIONZONE,
	RETURNVALUE_YOUMAYNOTATTACKTHISPLAYER,
	RETURNVALUE_YOUMAYNOTATTACKAPERSONINPROTECTIONZONE,
	RETURNVALUE_YOUMAYNOTATTACKAPERSONWHILEINPROTECTIONZONE,
	RETURNVALUE_YOUMAYNOTATTACKTHISCREATURE,
	RETURNVALUE_YOUCANONLYUSEITONCREATURES,
	RETURNVALUE_CREATUREISNOTREACHABLE,
	RETURNVALUE_TURNSECUREMODETOATTACKUNMARKEDPLAYERS,
	RETURNVALUE_YOUNEEDPREMIUMACCOUNT,
	RETURNVALUE_YOUNEEDTOLEARNTHISSPELL,
	RETURNVALUE_YOURVOCATIONCANNOTUSETHISSPELL,
	RETURNVALUE_YOUNEEDAWEAPONTOUSETHISSPELL,
	RETURNVALUE_PLAYERISPZLOCKEDLEAVEPVPZONE,
	RETURNVALUE_PLAYERISPZLOCKEDENTERPVPZONE,
	RETURNVALUE_ACTIONNOTPERMITTEDINANOPVPZONE,
	RETURNVALUE_YOUCANNOTLOGOUTHERE,
	RETURNVALUE_YOUNEEDAMAGICITEMTOCASTSPELL,
	RETURNVALUE_NAMEISTOOAMBIGUOUS,
	RETURNVALUE_CANONLYUSEONESHIELD,
	RETURNVALUE_NOPARTYMEMBERSINRANGE,
	RETURNVALUE_YOUARENOTTHEOWNER,
	RETURNVALUE_TRADEPLAYERFARAWAY,
	RETURNVALUE_YOUDONTOWNTHISHOUSE,
	RETURNVALUE_TRADEPLAYERALREADYOWNSAHOUSE,
	RETURNVALUE_TRADEPLAYERHIGHESTBIDDER,
	RETURNVALUE_YOUCANNOTTRADETHISHOUSE,
	RETURNVALUE_YOUDONTHAVEREQUIREDPROFESSION,
	RETURNVALUE_CANNOTMOVEITEMISNOTSTOREITEM,
	RETURNVALUE_ITEMCANNOTBEMOVEDTHERE,
	RETURNVALUE_YOUCANNOTUSETHISBED,
	RETURNVALUE_QUIVERAMMOONLY,
};

enum SpeechBubble_t
{
	SPEECHBUBBLE_NONE = 0,
	SPEECHBUBBLE_NORMAL = 1,
	SPEECHBUBBLE_TRADE = 2,
	SPEECHBUBBLE_QUEST = 3,
	SPEECHBUBBLE_COMPASS = 4,
	SPEECHBUBBLE_NORMAL2 = 5,
	SPEECHBUBBLE_NORMAL3 = 6,
	SPEECHBUBBLE_HIRELING = 7,

	SPEECHBUBBLE_LAST = SPEECHBUBBLE_HIRELING
};

enum MapMark_t
{
	MAPMARK_TICK = 0,
	MAPMARK_QUESTION = 1,
	MAPMARK_EXCLAMATION = 2,
	MAPMARK_STAR = 3,
	MAPMARK_CROSS = 4,
	MAPMARK_TEMPLE = 5,
	MAPMARK_KISS = 6,
	MAPMARK_SHOVEL = 7,
	MAPMARK_SWORD = 8,
	MAPMARK_FLAG = 9,
	MAPMARK_LOCK = 10,
	MAPMARK_BAG = 11,
	MAPMARK_SKULL = 12,
	MAPMARK_DOLLAR = 13,
	MAPMARK_REDNORTH = 14,
	MAPMARK_REDSOUTH = 15,
	MAPMARK_REDEAST = 16,
	MAPMARK_REDWEST = 17,
	MAPMARK_GREENNORTH = 18,
	MAPMARK_GREENSOUTH = 19,
};

struct Outfit_t
{
	uint16_t lookType = 0;
	uint16_t lookTypeEx = 0;
	uint8_t lookHead = 0;
	uint8_t lookBody = 0;
	uint8_t lookLegs = 0;
	uint8_t lookFeet = 0;
	uint8_t lookAddons = 0;
	uint16_t lookMount = 0;
	uint8_t lookMountHead = 0;
	uint8_t lookMountBody = 0;
	uint8_t lookMountLegs = 0;
	uint8_t lookMountFeet = 0;
};

struct LightInfo
{
	uint8_t level = 0;
	uint8_t color = 215;
	constexpr LightInfo() = default;
	constexpr LightInfo(uint8_t level, uint8_t color) : level(level), color(color) {}
};

struct ShopInfo
{
	uint16_t itemId = 0;
	int32_t subType = 1;
	int64_t buyPrice = 0;
	int64_t sellPrice = 0;
	std::string realName = "";

	ShopInfo() = default;
	ShopInfo(uint16_t itemId, int32_t subType = 0, int64_t buyPrice = 0, int64_t sellPrice = 0,
	         std::string realName = "") :
	    itemId(itemId), subType(subType), buyPrice(buyPrice), sellPrice(sellPrice), realName(std::move(realName))
	{}
};

struct MarketOffer
{
	uint64_t price;
	uint32_t timestamp;
	uint16_t amount;
	uint16_t counter;
	uint16_t itemId;
	std::string playerName;
};

struct MarketOfferEx
{
	MarketOfferEx() = default;
	MarketOfferEx(MarketOfferEx&& other) :
	    id(other.id),
	    playerId(other.playerId),
	    timestamp(other.timestamp),
	    price(other.price),
	    amount(other.amount),
	    counter(other.counter),
	    itemId(other.itemId),
	    type(other.type),
	    playerName(std::move(other.playerName))
	{}

	uint32_t id;
	uint32_t playerId;
	uint32_t timestamp;
	uint64_t price;
	uint16_t amount;
	uint16_t counter;
	uint16_t itemId;
	MarketAction_t type;
	std::string playerName;
};

struct HistoryMarketOffer
{
	uint32_t timestamp;
	uint64_t price;
	uint16_t itemId;
	uint16_t amount;
	MarketOfferState_t state;
};

struct MarketStatistics
{
	uint32_t numTransactions = 0;
	uint32_t highestPrice = 0;
	uint64_t totalPrice = 0;
	uint32_t lowestPrice = 0;
};

struct ModalWindow
{
	std::list<std::pair<std::string, uint8_t>> buttons, choices;
	std::string title, message;
	uint32_t id;
	uint8_t defaultEnterButton = 0xFF, defaultEscapeButton = 0xFF;
	bool priority = false;

	ModalWindow(uint32_t id, std::string title, std::string message) :
	    title(std::move(title)), message(std::move(message)), id(id)
	{}
};

enum CombatOrigin
{
	ORIGIN_NONE,
	ORIGIN_CONDITION,
	ORIGIN_SPELL,
	ORIGIN_MELEE,
	ORIGIN_RANGED,
	ORIGIN_WAND,
	ORIGIN_REFLECT,
};

struct CombatDamage
{
	struct
	{
		CombatType_t type = COMBAT_NONE;
		int32_t value = 0;
	} primary = {}, secondary = {};

	CombatOrigin origin = ORIGIN_NONE;
	BlockType_t blockType = BLOCK_NONE;
	bool critical = false;
	bool leeched = false;
};

using MarketOfferList = std::list<MarketOffer>;
using HistoryMarketOfferList = std::list<HistoryMarketOffer>;
using ShopInfoList = std::list<ShopInfo>;

enum MonstersEvent_t : uint8_t
{
	MONSTERS_EVENT_NONE = 0,
	MONSTERS_EVENT_THINK = 1,
	MONSTERS_EVENT_APPEAR = 2,
	MONSTERS_EVENT_DISAPPEAR = 3,
	MONSTERS_EVENT_MOVE = 4,
	MONSTERS_EVENT_SAY = 5,
};

struct Reflect
{
	Reflect() = default;
	Reflect(uint16_t percent, uint16_t chance) : percent(percent), chance(chance){};

	Reflect& operator+=(const Reflect& other)
	{
		percent += other.percent;
		chance = std::min<uint16_t>(100, chance + other.chance);
		return *this;
	}

	uint16_t percent = 0;
	uint16_t chance = 0;
};

enum ClientDamageType
{
	CLIENT_DAMAGETYPE_PHYSICAL = 0,
	CLIENT_DAMAGETYPE_FIRE = 1,
	CLIENT_DAMAGETYPE_EARTH = 2,
	CLIENT_DAMAGETYPE_ENERGY = 3,
	CLIENT_DAMAGETYPE_ICE = 4,
	CLIENT_DAMAGETYPE_HOLY = 5,
	CLIENT_DAMAGETYPE_DEATH = 6,
	CLIENT_DAMAGETYPE_HEALING = 7,
	CLIENT_DAMAGETYPE_DROWN = 8,
	CLIENT_DAMAGETYPE_LIFEDRAIN = 9,
	CLIENT_DAMAGETYPE_UNDEFINED = 10
};

enum DamageAnalyzerImpactType
{
	HEALING = 0,
	DEALT = 1,
	RECEIVED = 2
};

enum SourceEffect_t : uint8_t
{
	GLOBAL = 0,
	OWN = 1,
	OTHERS = 2,
	CREATURES = 3
};

enum SoundEffect_t : uint16_t
{
	SILENCE = 0,
	HUMAN_CLOSE_ATK_FIST = 1,
	MONSTER_CLOSE_ATK_FIST = 2,
	MELEE_ATK_SWORD = 3,
	MELEE_ATK_CLUB = 4,
	MELEE_ATK_AXE = 5,
	DIST_ATK_BOW = 6,
	DIST_ATK_CROSSBOW = 7,
	DIST_ATK_THROW = 8,
	MAGICAL_RANGE_ATK = 9,
	SPELL_OR_RUNE = 10,
	OTHER = 11,
	PHYSICAL_RANGE_MISS = 12,
	DIST_ATK_BOW_SHOT = 13,
	DIST_ATK_CROSSBOW_SHOT = 14,
	DIST_ATK_THROW_SHOT = 15,
	DIST_ATK_ROD_SHOT = 16,
	DIST_ATK_WAND_SHOT = 17,
	BURST_ARROW_EFFECT = 18,
	DIAMOND_ARROW_EFFECT = 19,
	NO_DAMAGE = 20,
	MONSTER_MELEE_ATK_FIST = 100,
	MONSTER_MELEE_ATK_CLAW = 101,
	MONSTER_MELEE_ATK_BITE = 102,
	MONSTER_MELEE_ATK_RIP = 103,
	MONSTER_MELEE_ATK_ACID = 104,
	MONSTER_MELEE_ATK_MAGIC = 105,
	MONSTER_MELEE_ATK_ETHEREAL = 106,
	MONSTER_MELEE_ATK_CONSTRUCT = 107,
	SPELL_LIGHT_HEALING = 1001,
	SPELL_INTENSE_HEALING = 1002,
	SPELL_ULTIMATE_HEALING = 1003,
	SPELL_INTENSE_HEALING_RUNE = 1004,
	SPELL_ULTIMATE_HEALING_RUNE = 1005,
	SPELL_HASTE = 1006,
	SPELL_LIGHT_MAGIC_MISSILE_RUNE = 1007,
	SPELL_HEAVY_MAGIC_MISSILE_RUNE = 1008,
	SPELL_SUMMON_CREATURE = 1009,
	SPELL_LIGHT = 1010,
	SPELL_GREAT_LIGHT = 1011,
	SPELL_CONVINCE_CREATURE_RUNE = 1012,
	SPELL_ENERGY_WAVE = 1013,
	SPELL_CHAMELEON_RUNE = 1014,
	SPELL_FIREBALL_RUNE = 1015,
	SPELL_GREAT_FIREBALL_RUNE = 1016,
	SPELL_FIRE_BOMB_RUNE = 1017,
	SPELL_EXPLOSION_RUNE = 1018,
	SPELL_FIRE_WAVE = 1019,
	SPELL_FIND_PERSON = 1020,
	SPELL_SUDDENDEATH_RUNE = 1021,
	SPELL_ENERGY_BEAM = 1022,
	SPELL_GREAT_ENERGY_BEAM = 1023,
	SPELL_HELL_SCORE = 1024,
	SPELL_FIRE_FIELD_RUNE = 1025,
	SPELL_POISON_FIELD_RUNE = 1026,
	SPELL_ENERGY_FIELD_RUNE = 1027,
	SPELL_FIRE_WALL_RUNE = 1028,
	SPELL_CURE_POISON = 1029,
	SPELL_DESTROY_FIELD_RUNE = 1030,
	SPELL_CURE_POISON_RUNE = 1031,
	SPELL_POISON_WALL_RUNE = 1032,
	SPELL_ENERGY_WALL_RUNE = 1033,
	SPELL_SALVATION = 1036,
	SPELL_CREATURE_ILLUSION = 1038,
	SPELL_STRONG_HASTE = 1039,
	SPELL_FOOD = 1042,
	SPELL_STRONG_ICE_WAVE = 1043,
	SPELL_MAGIC_SHIELD = 1044,
	SPELL_INVISIBLE = 1045,
	SPELL_CONJURE_EXPLOSIVE_ARROW = 1049,
	SPELL_SOUL_FIRE_RUNE = 1050,
	SPELL_CONJURE_ARROW = 1051,
	SPELL_PARALYSE_RUNE = 1054,
	SPELL_ENERGY_BOMB_RUNE = 1055,
	SPELL_WRATH_OF_NATURE = 1056,
	SPELL_STRONG_ETHEREAL_SPEAR = 1057,
	SPELL_FRONT_SWEEP = 1059,
	SPELL_BRUTAL_STRIKE = 1061,
	SPELL_ANNIHILATION = 1062,
	SPELL_INVITE_GUESTS = 1071,
	SPELL_INVITE_SUBOWNERS = 1072,
	SPELL_KICK_GUEST = 1073,
	SPELL_EDIT_DOOR = 1074,
	SPELL_ULTIMATE_LIGHT = 1075,
	SPELL_MAGIC_ROPE = 1076,
	SPELL_STALAGMITE_RUNE = 1077,
	SPELL_DISINTEGRATE_RUNE = 1078,
	SPELL_BERSERK = 1080,
	SPELL_LEVITATE = 1081,
	SPELL_MASS_HEALING = 1082,
	SPELL_ANIMATE_DEAD_RUNE = 1083,
	SPELL_HEAL_FRIEND = 1084,
	SPELL_UNDEAD_LEGION = 1085,
	SPELL_MAGIC_WALL_RUNE = 1086,
	SPELL_DEATH_STRIKE = 1087,
	SPELL_ENERGY_STRIKE = 1088,
	SPELL_FLAME_STRIKE = 1089,
	SPELL_CANCEL_INVISIBILITY = 1090,
	SPELL_POISON_BOMB_RUNE = 1091,
	SPELL_CONJURE_WAND_OF_DARKNESS = 1092,
	SPELL_CHALLENGE = 1093,
	SPELL_WILD_GROWTH_RUNE = 1094,
	SPELL_FIERCE_BERSERK = 1105,
	SPELL_GROUNDSHAKER = 1106,
	SPELL_WHIRLWIND_THROW = 1107,
	SPELL_ENCHANT_SPEAR = 1110,
	SPELL_ETHEREAL_SPEAR = 1111,
	SPELL_ICE_STRIKE = 1112,
	SPELL_TERRA_STRIKE = 1113,
	SPELL_ICICLE_RUNE = 1114,
	SPELL_AVALANCHE_RUNE = 1115,
	SPELL_STONE_SHOWER_RUNE = 1116,
	SPELL_THUNDERSTORM_RUNE = 1117,
	SPELL_ETERNAL_WINTER = 1118,
	SPELL_RAGE_OF_THE_SKIES = 1119,
	SPELL_TERRA_WAVE = 1120,
	SPELL_ICE_WAVE = 1121,
	SPELL_DIVINE_MISSILE = 1122,
	SPELL_WOUND_CLEANSING = 1123,
	SPELL_DIVINE_CALDERA = 1124,
	SPELL_DIVINE_HEALING = 1125,
	SPELL_TRAIN_PARTY = 1126,
	SPELL_PROTECT_PARTY = 1127,
	SPELL_HEAL_PARTY = 1128,
	SPELL_ENCHANT_PARTY = 1129,
	SPELL_HOLY_MISSILE_RUNE = 1130,
	SPELL_CHARGE = 1131,
	SPELL_PROTECTOR = 1132,
	SPELL_BLOOD_RAGE = 1133,
	SPELL_SWIFT_FOOT = 1134,
	SPELL_SHARPSHOOTER = 1135,
	SPELL_IGNITE = 1138,
	SPELL_CURSE = 1139,
	SPELL_ELECTRIFY = 1140,
	SPELL_INFLICT_WOUND = 1141,
	SPELL_ENVENOM = 1142,
	SPELL_HOLY_FLASH = 1143,
	SPELL_CURE_BLEEDING = 1144,
	SPELL_CURE_BURNING = 1145,
	SPELL_CURE_ELECTRIFICATION = 1146,
	SPELL_CURE_CURSE = 1147,
	SPELL_PHYSICAL_STRIKE = 1148,
	SPELL_LIGHTNING = 1149,
	SPELL_STRONG_FLAME_STRIKE = 1150,
	SPELL_STRONG_ENERGY_STRIKE = 1151,
	SPELL_STRONG_ICE_STRIKE = 1152,
	SPELL_STRONG_TERRA_STRIKE = 1153,
	SPELL_ULTIMATE_FLAME_STRIKE = 1154,
	SPELL_ULTIMATE_ENERGY_STRIKE = 1155,
	SPELL_ULTIMATE_ICE_STRIKE = 1156,
	SPELL_ULTIMATE_TERRA_STRIKE = 1157,
	SPELL_INTENSE_WOUND_CLEANSING = 1158,
	SPELL_RECOVERY = 1159,
	SPELL_INTENSE_RECOVERY = 1160,
	SPELL_PRACTISE_HEALING = 1166,
	SPELL_PRACTISE_FIRE_WAVE = 1167,
	SPELL_PRACTISE_MAGIC_MISSILE_RUNE = 1168,
	SPELL_APPRENT_ICES_STRIKE = 1169,
	SPELL_MUD_ATTACK = 1172,
	SPELL_CHILL_OUT = 1173,
	SPELL_MAGIC_PATCH = 1174,
	SPELL_BRUISE_BANE = 1175,
	SPELL_ARROW_CALL = 1176,
	SPELL_BUZZ = 1177,
	SPELL_SCORCH = 1178,
	SPELL_LIGHTEST_MISSILE_RUNE = 1179,
	SPELL_LIGHT_STONE_SHOWER_RUNE = 1180,
	SPELL_SUMMON_KNIGHT_FAMILIAR = 1194,
	SPELL_SUMMON_PALADIN_FAMILIAR = 1195,
	SPELL_SUMMON_SORCERER_FAMILIAR = 1196,
	SPELL_SUMMON_DRUID_FAMILIAR = 1197,
	SPELL_CHIVALROUS_CHALLENGE = 1237,
	SPELL_DIVINE_DAZZLE = 1238,
	SPELL_FAIR_WOUND_CLEANSING = 1239,
	SPELL_GREAT_FIRE_WAVE = 1240,
	SPELL_RESTORATION = 1241,
	SPELL_NATURES_EMBRACE = 1242,
	SPELL_EXPOSE_WEAKNESS = 1243,
	SPELL_SAP_STRENGTH = 1244,
	SPELL_CANCEL_MAGIC_SHIELD = 1245,
	MONSTER_SPELL_SINGLE_TARGET_FIRE = 2002,
	MONSTER_SPELL_SINGLE_TARGET_ENERGY = 2003,
	MONSTER_SPELL_SINGLE_TARGET_EARTH = 2004,
	MONSTER_SPELL_SINGLE_TARGET_ICE = 2005,
	MONSTER_SPELL_SINGLE_TARGET_DEATH = 2006,
	MONSTER_SPELL_SINGLE_TARGET_HOLY = 2007,
	MONSTER_SPELL_SINGLE_TARGET_HIT = 2008,
	MONSTER_SPELL_SINGLE_TARGET_LIFEDRAIN = 2009,
	MONSTER_SPELL_SINGLE_TARGET_MANADRAIN = 2010,
	MONSTER_SPELL_SINGLE_TARGET_DROWNING = 2011,
	MONSTER_SPELL_SINGLE_TARGET_BLEEDING = 2012,
	MONSTER_SPELL_SINGLE_TARGET_HEALING = 2013,
	MONSTER_SPELL_SMALL_AREA_FIRE = 2015,
	MONSTER_SPELL_SMALL_AREA_ENERGY = 2016,
	MONSTER_SPELL_SMALL_AREA_EARTH = 2017,
	MONSTER_SPELL_SMALL_AREA_ICE = 2018,
	MONSTER_SPELL_SMALL_AREA_DEATH = 2019,
	MONSTER_SPELL_SMALL_AREA_HOLY = 2020,
	MONSTER_SPELL_SMALL_AREA_HIT = 2021,
	MONSTER_SPELL_SMALL_AREA_LIFEDRAIN = 2022,
	MONSTER_SPELL_SMALL_AREA_MANADRAIN = 2023,
	MONSTER_SPELL_SMALL_AREA_DROWNING = 2024,
	MONSTER_SPELL_SMALL_AREA_BLEEDING = 2025,
	MONSTER_SPELL_SMALL_AREA_HEALING = 2026,
	MONSTER_SPELL_LARGE_AREA_FIRE = 2028,
	MONSTER_SPELL_LARGE_AREA_ENERGY = 2029,
	MONSTER_SPELL_LARGE_AREA_EARTH = 2030,
	MONSTER_SPELL_LARGE_AREA_ICE = 2031,
	MONSTER_SPELL_LARGE_AREA_DEATH = 2032,
	MONSTER_SPELL_LARGE_AREA_HOLY = 2033,
	MONSTER_SPELL_LARGE_AREA_HIT = 2034,
	MONSTER_SPELL_LARGE_AREA_LIFEDRAIN = 2035,
	MONSTER_SPELL_LARGE_AREA_MANADRAIN = 2036,
	MONSTER_SPELL_LARGE_AREA_DROWNING = 2037,
	MONSTER_SPELL_LARGE_AREA_BLEEDING = 2038,
	MONSTER_SPELL_LARGE_AREA_HEALING = 2039,
	MONSTER_SPELL_WAVE_FIRE = 2041,
	MONSTER_SPELL_WAVE_ENERGY = 2042,
	MONSTER_SPELL_WAVE_EARTH = 2043,
	MONSTER_SPELL_WAVE_ICE = 2044,
	MONSTER_SPELL_WAVE_DEATH = 2045,
	MONSTER_SPELL_WAVE_HOLY = 2046,
	MONSTER_SPELL_WAVE_HIT = 2047,
	MONSTER_SPELL_WAVE_LIFEDRAIN = 2048,
	MONSTER_SPELL_WAVE_MANADRAIN = 2049,
	MONSTER_SPELL_WAVE_DROWNING = 2050,
	MONSTER_SPELL_WAVE_BLEEDING = 2051,
	MONSTER_SPELL_WAVE_HEALING = 2052,
	MONSTER_SPELL_DELETEFIELD = 2054,
	MONSTER_SPELL_CHALLENGE = 2055,
	MONSTER_SPELL_SPEED = 2056,
	MONSTER_SPELL_DRUNKEN = 2057,
	MONSTER_SPELL_STRENGTH = 2058,
	MONSTER_SPELL_OUTFIT = 2059,
	MONSTER_SPELL_SUMMON = 2060,
	MONSTER_SPELL_MAGICLEVEL = 2061,
	MONSTER_SPELL_TELEPORT = 2062,
	MONSTER_SPELL_HEX = 2063,
	MONSTER_SPELL_SUPER_DRUNKEN = 2064,
	MONSTER_SPELL_ROOT = 2065,
	MONSTER_SPELL_FEAR = 2066,
	MONSTER_SPELL_HIGHRISK_TELEPORT = 2067,
	MONSTER_SPELL_MINION = 2068,
	MONSTER_SPELL_AGONY = 2069,
	AMPHIBIC_BARK = 2500,
	AQUATIC_BEAST_BARK = 2501,
	AQUATIC_CRITTER_BARK = 2502,
	AQUATIC_DEEPLING_BARK = 2503,
	AQUATIC_QUARA_BARK = 2504,
	BIRD_BARK = 2505,
	CONSTRUCT_BARK = 2506,
	DEMON_BARK = 2507,
	DRAGON_BARK = 2508,
	ELEMENTAL_EARTH_BARK = 2509,
	ELEMENTAL_ENERGY_BARK = 2510,
	ELEMENTAL_FIRE_BARK = 2511,
	ELEMENTAL_WATER_BARK = 2512,
	EXTRA_DIMENSIONAL_BEAST_BARK = 2513,
	EXTRA_DIMENSIONAL_ENERGY_BARK = 2514,
	EXTRA_DIMENSIONAL_HORROR_BARK = 2515,
	FEY_BARK = 2516,
	GIANT_BARK = 2517,
	HUMAN_FEMALE_BARK = 2518,
	HUMAN_MALE_BARK = 2519,
	HUMANOID_GOBLIN_BARK = 2520,
	HUMANOID_ORC_BARK = 2521,
	LYCANTHROPE_BARK = 2522,
	MAGICAL_ENERGY_BARK = 2523,
	MAGICAL_HORROR_BARK = 2524,
	MAMMAL_BEAR_BARK = 2525,
	MAMMAL_CRITTER_BARK = 2526,
	MAMMAL_DOG_BARK = 2527,
	MAMMAL_ELEPHANT_BARK = 2528,
	MAMMAL_FERAL_BARK = 2529,
	MAMMAL_HORSE_BARK = 2530,
	MAMMAL_MAMMOTH_BARK = 2531,
	MONSTER_BARK = 2532,
	PHANTOM_BARK = 2533,
	PLANT_BARK = 2534,
	REPTILE_LARGE_BARK = 2535,
	REPTILE_SMALL_BARK = 2536,
	SLIME_BARK = 2537,
	UNDEAD_BARK = 2538,
	VERMIN_CRITTER_BARK = 2539,
	VERMIN_INSECT_BARK = 2540,
	VERMIN_ROTWORM_BARK = 2541,
	HUMAN_SAGE_BARK = 2542,
	HUMAN_CRONE_BARK = 2543,
	APE_BARK = 2544,
	AMPHIBIC_DEATH = 2600,
	AQUATIC_BEAST_DEATH = 2601,
	AQUATIC_CRITTER_DEATH = 2602,
	AQUATIC_DEEPLING_DEATH = 2603,
	AQUATIC_QUARA_DEATH = 2604,
	BIRD_DEATH = 2605,
	CONSTRUCT_DEATH = 2606,
	DEMON_DEATH = 2607,
	DRAGON_DEATH = 2608,
	ELEMENTAL_EARTH_DEATH = 2609,
	ELEMENTAL_ENERGY_DEATH = 2610,
	ELEMENTAL_FIRE_DEATH = 2611,
	ELEMENTAL_WATER_DEATH = 2612,
	EXTRA_DIMENSIONAL_BEAST_DEATH = 2613,
	EXTRA_DIMENSIONAL_ENERGY_DEATH = 2614,
	EXTRA_DIMENSIONAL_HORROR_DEATH = 2615,
	FEY_DEATH = 2616,
	GIANT_DEATH = 2617,
	HUMAN_FEMALE_DEATH = 2618,
	HUMAN_MALE_DEATH = 2619,
	HUMANOID_GOBLIN_DEATH = 2620,
	HUMANOID_ORC_DEATH = 2621,
	LYCANTHROPE_DEATH = 2622,
	MAGICAL_ENERGY_DEATH = 2623,
	MAGICAL_HORROR_DEATH = 2624,
	MAMMAL_BEAR_DEATH = 2625,
	MAMMAL_CRITTER_DEATH = 2626,
	MAMMAL_DOG_DEATH = 2627,
	MAMMAL_ELEPHANT_DEATH = 2628,
	MAMMAL_FERAL_DEATH = 2629,
	MAMMAL_HORSE_DEATH = 2630,
	MAMMAL_MAMMOTH_DEATH = 2631,
	MONSTER_DEATH = 2632,
	PHANTOM_DEATH = 2633,
	PLANT_DEATH = 2634,
	REPTILE_LARGE_DEATH = 2635,
	REPTILE_SMALL_DEATH = 2636,
	SLIME_DEATH = 2637,
	UNDEAD_DEATH = 2638,
	VERMIN_CRITTER_DEATH = 2639,
	VERMIN_INSECT_DEATH = 2640,
	VERMIN_ROTWORM_DEATH = 2641,
	HUMAN_SAGE_DEATH = 2642,
	HUMAN_CRONE_DEATH = 2643,
	APE_DEATH = 2644,
	UNKNOWN_CREATURE_DEATH_1 = 2645,
	UNKNOWN_CREATURE_DEATH_2 = 2646,
	UNKNOWN_CREATURE_DEATH_3 = 2647,
	UNKNOWN_CREATURE_DEATH_4 = 2648,
	ACTION_HEAVY_METAL_LOUD = 2649,
	ENV_INSECTS_BIRDS = 2651,
	ENV_WIND_1 = 2652,
	ENV_WIND_CLOSE = 2653,
	ENV_WATER_DEPTH_BOAT_SURFACE = 2654,
	ENV_METALIC_SPACE = 2655,
	ENV_FROGS_INSECTS_WOODS = 2656,
	ENV_WATER_DEPTH = 2657,
	ENV_SEA_WAVE = 2658,
	ENV_WIND_2 = 2659,
	ENV_WIND_3 = 2660,
	ENV_MONKEYS = 2661,
	ENV_STORM_COMING = 2662,
	ACTION_HITTING_WOOD = 2663,
	ENV_WOOD_STICK_SMASH = 2664,
	ENV_THICK_BLOB_LIQUID_1 = 2665,
	ENV_LITTLE_BIRTS_FLOREST = 2666,
	ENV_THICK_BLOCK_LIQUID_CLOSE = 2667,
	ACTION_METAL_CHAINS_MOVING = 2668,
	ENV_CRICKET_1 = 2669,
	ENV_CRICKET_2 = 2670,
	ENV_CRICKET_3 = 2671,
	ENV_CICADA_1 = 2672,
	ENV_STONES_FALLING = 2673,
	ACTION_OPEN_DOOR = 2674,
	ACTION_CLOSE_DOOR = 2675,
	ENV_OWL = 2676,
	ENV_ELETRONIC_DEVICE = 2678,
	ENV_REPTILE_NOISE = 2679,
	ENV_FORGE_METAL_1 = 2680,
	ENV_FROG = 2681,
	ACTION_WOOD_OBJECT_USING = 2682,
	ACTION_METAL_OBJECT_HIT = 2683,
	ACTION_NAIL_HIT = 2684,
	ENV_BELL_RING = 2685,
	ENV_HOT_METAL_ON_WATER = 2686,
	ENV_WATER_SMOKE = 2687,
	ENV_WOLF_HOWL = 2688,
	ENV_WOOD_CRACKLE_CLOSE = 2689,
	ENV_LAUGHT = 2690,
	ENV_WIND_MOVING_LEAF = 2691,
	ENV_WIND_MOVING_FEW_LEAF = 2692,
	ACTION_PORTAL_CAST = 2693,
	ACTION_FIRE_MAGIC_CAST = 2694,
	ENV_TRAPDOOR_OPEN = 2695,
	ENV_NAIL_FALLING = 2696,
	ENV_LIGHT_BLOB_LIQUID = 2697,
	ENV_LION_ROAR = 2698,
	ENV_MOVING_OBJECT_BUTTON_TRIGGER = 2699,
	ENV_SNAKE_1 = 2700,
	ENV_HUMAN_SCREEN_1 = 2701,
	ENV_HUMAN_SCREEN_2 = 2702,
	ENV_SEAGUL_1 = 2703,
	ENV_FAST_FOOTSTEPS = 2704,
	ENV_SLOW_FOOTSTEPS = 2705,
	ENV_THICK_BLOB_LIQUID_2 = 2706,
	ENV_MOVING_LEAF = 2707,
	ENV_WOOD_CRACKLE_1 = 2708,
	ACTION_OBJECT_FALLING_DEPTH = 2709,
	ACTION_BUTTON_TRIGGER = 2710,
	ENV_HEAVEN_DARK_REVERB = 2711,
	ENV_WIND_4 = 2712,
	ENV_INSECT_1 = 2713,
	ENV_FLUTE_SONG = 2714,
	ENV_INSECTS_BIRDS_DEATH = 2715,
	ENV_INSECT_CREATURE_DEATH = 2716,
	ENV_LOW_ROAR = 2717,
	ENV_SINISTER_BURPH = 2718,
	ENV_CROWD_SCREEN = 2719,
	ENV_BIRDS_FLYING = 2720,
	ENV_CROWD_VOICES_1 = 2721,
	ENV_BIRD_CUCO = 2722,
	ENV_RAVINE = 2723,
	ENV_RAVINE_METALIC = 2724,
	ENV_STICKS_LEAF_STEP = 2725,
	ACTION_DISPEL_MAGIC_1 = 2726,
	ACTION_DISPEL_MAGIC_2 = 2727,
	ENV_CROWD_VOICES_2 = 2728,
	ENV_CROWD_VOICES_3 = 2729,
	ENV_CROWD_VOICES_4 = 2730,
	ACTION_METAL_OBJECT_FALL = 2731,
	ENV_HOURSE_STEPS = 2732,
	ENV_DRUMES_SINISTER_REVERB = 2733,
	ACTION_WOOD_PIECES_FALL = 2734,
	ACTION_KNIFE_CUT_FLESH = 2735,
	ENV_CROWD_VOICES_5 = 2736,
	ENV_CICADA_2 = 2738,
	ENV_FLYES = 2739,
	ENV_NOISE_WATER = 2740,
	ENV_PIG_SOUND_1 = 2741,
	ENV_PIG_SOUND_2 = 2742,
	ENV_SHEEP_SOUND_1 = 2743,
	ENV_SHEEP_SOUND_2 = 2744,
	ENV_FIRE = 2745,
	ENV_NOISE_SNOW = 2746,
	ENV_FIRE_PLACE = 2747,
	ENV_WATERFALL = 2748,
	ENV_WATER_SOURCE = 2749,
	ACTION_HAMMER_HITING_NAILS_1 = 2750,
	ACTION_HAMMER_HITING_NAILS_2 = 2751,
	ENV_QUICK_STEPS = 2752,
	ENV_HEAVY_OBJECT_FALL = 2753,
	ACTION_HITING_FORGE = 2754,
	ENV_WOOD_CRACKLE_2 = 2755,
	ACTION_WOOD_HIT = 2756,
	MUSIC_CUT_BIRDS = 2757,
	MUSIC_CUT_LITTLE_BIRDS = 2758,
	MUSIC_CUT_INSECTS_1 = 2759,
	MUSIC_CUT_INSECTS_2 = 2760,
	MUSIC_CUT_INSECTS_3 = 2761,
	MUSIC_CUT_FLUTE_WEST = 2762,
	MUSIC_CUT_CROWS_VOICES = 2763,
	MUSIC_CUT_WIND_WATER = 2764,
	MUSIC_CUT_THICK_BLOCK_DEPTH = 2765,
	ENV_CAMEL = 2766,
	UNKNOWN_CREATURE_DEATH_5 = 2767,
	ENV_CHICKEN_1 = 2768,
	ENV_CHICKEN_2 = 2769,
	ENV_THRILLER_METALLIC = 2770,
	ACTION_NOTIFICATION = 2771,
	ACTION_LEVEL_ACHIEVEMENT = 2772,
	ACTION_SCREENSHOT = 2773,
	ACTION_CLICK_ON = 2774,
	ACTION_CLICK_OFF = 2775,
	ACTION_DRUMS = 2776,
	ACTION_XYLOPHONE_SLOW_DRUM = 2777,
	ACTION_HARP_1 = 2778,
	ACTION_HARP_2 = 2779,
	ACTION_MOVING_WOOD = 2780,
	ACTION_CRATE_BREAK_MAGIC_DUST = 2781,
	ACTION_BELL_RING = 2783,
	ACTION_SELECT_OBJECT = 2785,
	ITEM_MOVE_BACKPACK = 2786,
	ITEM_USE_POTION = 2787,
	ITEM_MOVE_NECKLACES = 2788,
	ITEM_MOVE_ARMORS = 2789,
	ITEM_MOVE_METALIC = 2790,
	ITEM_MOVE_DISTANCE = 2791,
	ITEM_MOVE_WOOD = 2792,
	ITEM_MOVE_STACKABLE = 2793,
	ITEM_MOVE_DEFAULT = 2794,
	ITEM_MOVE_LEGS = 2795,
	ITEM_MOVE_HELMETS = 2796,
	ITEM_MOVE_QUIVERS = 2797,
	ITEM_MOVE_RINGS = 2798,
	ENV_FROG_OR_LIQUID = 2799,
	ACTION_WOOD_OBJECT_HIT_STORE = 2800,
	ITEM_MOVE_BOOTS = 2801,
	ACTION_SWORD_DRAWN = 2802,
	ACTION_EAT = 2803,
	ACTION_STORE_BIG_OBJECT = 2804,
	ACTION_STORE_WOOD_OBJECT = 2805,
	ACTION_VIP_LOGOUT = 2806,
	ACTION_VIP_LOGIN = 2807,
	ENV_CAT_1 = 2808,
	ENV_INSECT_2 = 2809,
	ENV_SEAGUL_2 = 2810,
	ENV_LIQUID_SPILL = 2811,
	ENV_COW_MOO_1 = 2813,
	ENV_COW_MOO_2 = 2814,
	ENV_CAT_2 = 2815,
	ACTION_REAWRD_FEY = 2816,
	ACTION_REWARD_GUITAR_1 = 2817,
	ACTION_REWARD_GUITAR_2 = 2818,
	ENV_WOODS_WATER_SOURCE = 2819,
	ENV_HYENA = 2820,
	UNKNOWN_CREATURE_DEATH_6 = 2821,
	ENV_COW_MOO_3 = 2822,
	UNKNOWN_CREATURE_DEATH_7 = 2823,
	ENV_METALIC_SPACE_ALIEN = 2824,
	ACTION_AIR_STRIKE = 2825,
	ENV_WATER = 2828,
	ENV_SNAKE_2 = 2829,
	GOD_SPELL_KILL_ALL_MONSTERS = 10001
};

#endif // FS_ENUMS_H
