name: Check code style

on:
  push:
    branches:
      - master
      - v*

    paths:
      - .clang-format
      - src/**

  pull_request:
    paths:
      - .clang-format
      - src/**

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update -q && sudo apt install -yq clang-format

      - name: Check code style
        run: clang-format -n -style=file --Werror src/*.{cpp,h}
